services:
  backend:
    build:
      context: ./academy-os-api
      dockerfile: Dockerfile
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./academy-os-api:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build:
      context: ./academy-os-client
      dockerfile: Dockerfile
    container_name: react_frontend
    command: npm run dev -- --host 0.0.0.0
    volumes:
      # Montage des sources locales pour le Hot-Reload (live changes)
      - ./academy-os-client:/app
      # Volume dédié pour préserver les node_modules Linux installés dans le conteneur
      - client_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    depends_on:
      - backend

  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: redis_cache
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
  client_node_modules:
