# Generated by Django 5.2 on 2026-08-18 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format de numéro de téléphone invalide.', regex='^\\+?[0-9\\s\\-()]{7,20}$')]),
        ),
    ]
