# Generated by Django 5.2 on 2026-08-16 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours_validation', 'En cours de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=30)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='programs.program')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['program', 'ordre', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('program', 'ordre'), name='unique_project_order_per_program')],
            },
        ),
    ]
