# Generated by Django 5.2 on 2026-08-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['program', 'order', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_project_order_per_program',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ordre',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Non publié'), ('published', 'Publié')], default='draft', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('program', 'order'), name='unique_project_order_per_program'),
        ),
    ]
