# Generated by Django 5.2 on 2026-08-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_deleted_at_alter_program_title_and_more'),
        ('projects', '0003_add_min_value_validator_to_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_project_order_per_program',
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('program', 'order'), name='unique_project_order_per_program'),
        ),
    ]
