# Generated by Django 5.2 on 2026-08-18 09:17

import apps.attachments.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.attachments.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'zip', 'png', 'jpg', 'jpeg', 'txt', 'md', 'ipynb', 'py', 'js', 'java', 'c', 'cpp']), apps.attachments.models.validate_file_size])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
