# Generated by Django 5.2 on 2026-08-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_attachment_content_type_attachment_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
