# Generated by Django 5.2 on 2026-08-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
