# Generated by Django 5.2 on 2026-08-29 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_deleted_at'),
        ('claims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='claim',
            name='uniq_active_claim_per_certificate',
        ),
        migrations.AddField(
            model_name='claim',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ['pending', 'in_progress'])), fields=('certificate',), name='uniq_active_claim_per_certificate'),
        ),
    ]
