# Generated by Django 5.2 on 2026-08-20 10:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0002_trainerassignment_enrollment_and_more'),
        ('projects', '0002_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('submitted', 'Soumis'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline_override', models.DateTimeField(blank=True, null=True)),
                ('final_score', models.PositiveIntegerField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='cohorts.enrollment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='projects.project')),
            ],
            options={
                'db_table': 'project_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('repo_url', models.URLField(blank=True, default='', max_length=500)),
                ('live_url', models.URLField(blank=True, default='', max_length=500)),
                ('comments', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('submitted', 'Soumis'), ('in_review', 'En cours de correction'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='submitted', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, default='')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deliverables', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_deliverables', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='evaluations.projectassignment')),
            ],
            options={
                'db_table': 'deliverables',
                'ordering': ['assignment', '-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectassignment',
            constraint=models.UniqueConstraint(fields=('enrollment', 'project'), name='unique_assignment_per_enrollment_and_project'),
        ),
        migrations.AddConstraint(
            model_name='deliverable',
            constraint=models.UniqueConstraint(fields=('assignment', 'version'), name='unique_deliverable_version_per_assignment'),
        ),
    ]
