# Generated by Django 5.2 on 2026-08-21 12:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0002_trainerassignment_enrollment_and_more'),
        ('projects', '0002_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('competency_name', models.CharField(blank=True, default='', help_text='Nom du domaine de compétence (ex: Architecture, Backend, Frontend, DevOps)', max_length=255)),
                ('max_score', models.DecimalField(decimal_places=2, default=20.0, help_text='Note maximale possible pour ce critère', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Coefficient de pondération du critère dans le calcul global', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.PositiveIntegerField(default=1, help_text="Ordre d'affichage du critère dans la grille d'évaluation")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_criteria', to='projects.project')),
            ],
            options={
                'verbose_name': "Critère d'évaluation",
                'verbose_name_plural': "Critères d'évaluation",
                'db_table': 'evaluation_criteria',
                'ordering': ['project', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('submitted', 'Soumis'), ('validated', 'Validé')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline_override', models.DateTimeField(blank=True, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, help_text="Note finale obtenue sur l'assignation de projet", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='cohorts.enrollment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='projects.project')),
            ],
            options={
                'verbose_name': 'Assignation de projet',
                'verbose_name_plural': 'Assignations de projet',
                'db_table': 'project_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('repo_url', models.URLField(blank=True, default='', max_length=500)),
                ('live_url', models.URLField(blank=True, default='', max_length=500)),
                ('comments', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('submitted', 'Soumis'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='submitted', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Note attribuée pour cette version de livrable', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True, default='')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='evaluations.projectassignment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deliverables', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_deliverables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livrable',
                'verbose_name_plural': 'Livrables',
                'db_table': 'deliverables',
                'ordering': ['assignment', '-version'],
            },
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, help_text='Note attribuée pour ce critère', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('level', models.CharField(choices=[('not_acquired', 'Non acquis'), ('in_progress', "En cours d'acquisition"), ('acquired', 'Acquis'), ('mastered', 'Maîtrisé')], default='in_progress', max_length=20)),
                ('feedback', models.TextField(blank=True, default='', help_text='Feedback détaillé pour cette compétence / ce critère')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='evaluations.evaluationcriterion')),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='evaluations.deliverable')),
            ],
            options={
                'verbose_name': 'Note par critère',
                'verbose_name_plural': 'Notes par critère',
                'db_table': 'criterion_scores',
                'ordering': ['criterion__order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='evaluationcriterion',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='uniq_criterion_order_per_project'),
        ),
        migrations.AddConstraint(
            model_name='projectassignment',
            constraint=models.UniqueConstraint(fields=('enrollment', 'project'), name='unique_assignment_per_enrollment_and_project'),
        ),
        migrations.AddConstraint(
            model_name='deliverable',
            constraint=models.UniqueConstraint(fields=('assignment', 'version'), name='unique_deliverable_version_per_assignment'),
        ),
        migrations.AddConstraint(
            model_name='criterionscore',
            constraint=models.UniqueConstraint(fields=('deliverable', 'criterion'), name='uniq_score_per_deliverable_criterion'),
        ),
    ]
