# Generated by Django 5.2 on 2026-08-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='status',
            field=models.CharField(choices=[('submitted', 'Soumis'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='submitted', max_length=20),
        ),
    ]
