# Generated by Django 5.2 on 2026-08-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_alter_deliverable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('submitted', 'Soumis'), ('validated', 'Validé')], default='pending', max_length=20),
        ),
    ]
