# Generated by Django 5.2 on 2026-08-29 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_remove_enrollment_uniq_enrollment_cohort_user_and_more'),
        ('evaluations', '0003_remove_rejected_from_assignment'),
        ('projects', '0004_remove_project_unique_project_order_per_program_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='criterionscore',
            name='uniq_score_per_deliverable_criterion',
        ),
        migrations.RemoveConstraint(
            model_name='deliverable',
            name='unique_deliverable_version_per_assignment',
        ),
        migrations.RemoveConstraint(
            model_name='evaluationcriterion',
            name='uniq_criterion_order_per_project',
        ),
        migrations.RemoveConstraint(
            model_name='projectassignment',
            name='unique_assignment_per_enrollment_and_project',
        ),
        migrations.AddField(
            model_name='criterionscore',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationcriterion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='criterionscore',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('deliverable', 'criterion'), name='uniq_score_per_deliverable_criterion'),
        ),
        migrations.AddConstraint(
            model_name='deliverable',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('assignment', 'version'), name='unique_deliverable_version_per_assignment'),
        ),
        migrations.AddConstraint(
            model_name='evaluationcriterion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'order'), name='uniq_criterion_order_per_project'),
        ),
        migrations.AddConstraint(
            model_name='projectassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('enrollment', 'project'), name='unique_assignment_per_enrollment_and_project'),
        ),
    ]
