# Generated by Django 5.2 on 2026-09-01 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_remove_criterionscore_uniq_score_per_deliverable_criterion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterionscore',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Note attribuée pour ce critère', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note attribuée pour cette version de livrable', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='evaluationcriterion',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Note maximale possible pour ce critère', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Note finale obtenue sur l'assignation de projet", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
