# Generated by Django 5.2 on 2026-08-16 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_cohort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('a_venir', 'A venir'), ('en_cours', 'En cours'), ('termine', 'Termine')], default='a_venir', max_length=20),
        ),
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nb_membres', models.PositiveIntegerField(default=0)),
                ('nb_projets', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('terminee', 'Terminee')], default='active', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohortes', to='session_cohort.session')),
            ],
            options={
                'verbose_name': 'Cohorte',
                'verbose_name_plural': 'Cohortes',
                'db_table': 'cohortes',
                'ordering': ['-created_at'],
            },
        ),
    ]
