# Generated by Django 5.2 on 2026-08-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('title',), name='uniq_active_program_title'),
        ),
    ]
