# Generated by Django 5.2 on 2026-08-29 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_trainerassignment_enrollment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='uniq_enrollment_cohort_user',
        ),
        migrations.RemoveConstraint(
            model_name='trainerassignment',
            name='uniq_trainer_assignment_cohort_user',
        ),
        migrations.AddField(
            model_name='cohort',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerassignment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('cohort', 'user'), name='uniq_enrollment_cohort_user'),
        ),
        migrations.AddConstraint(
            model_name='trainerassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('cohort', 'user'), name='uniq_trainer_assignment_cohort_user'),
        ),
    ]
